# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "TebanCardona-Deploy-Frontend" ]
  pull_request:
    branches: [ "TebanCardona-Deploy-Frontend" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
  # REACT Deploy        
  # You may pin to the exact commit or the version.
  # uses: bitovi/github-actions-react-to-github-pages@b11ff1a0aa37ac7ef20f152904017e9ab1b31b56
    
    - name: Deploy React to GitHub Pages
      uses: bitovi/github-actions-react-to-github-pages@v1.2.2
      with:
      # Specifies if this action should checkout the code
        checkout: true 
        # optional, default is true
      # Specifies the path of the static assets after building
        shell: ls
        path: /client 
        # optional, default is dist
      # Specifies the command to run the installation.
        install_command: npm ci
      # Specifies the command to run after the install command for the build
        build_command: npm run build
          
